version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - mynetwork

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis_stack_container
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - mynetwork

volumes:
  postgres_data:
