version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  database:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  hono-app:
    build: .
    container_name: hono_app_container
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres_container:5432/mydb?schema=public"
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - mynetwork
