name: CI Workflow

on:
  push:
    branches:
      - main # Run this workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Generate Prisma Client
      - name: Generate Prisma Client
        run: npx prisma generate

      # Run Prisma Migrations
      - name: Run Prisma Migrations
        env:
          DATABASE_URL: "postgresql://postgres:password@localhost:5432/mydb?schema=public"
        run: npx prisma db push

      # Run Tests (Optional)
      - name: Run Tests
        env:
          DATABASE_URL: "postgresql://postgres:password@localhost:5432/mydb?schema=public"
        run: npm test

      # Build Docker Image (Optional)
      - name: Build Docker Image
        run: docker build -t myapp:latest .
